language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

install:
  pip install -r requirements.txt

script:
  pytest --cov=sbmlutils

after_success:
   pip install codecov; codecov
