# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEPLOYMENT
# build containers
#   docker-compose -f docker-compose-production.yml build --no-cache
#   docker-compose -f docker-compose-production.yml build
# serve containers
#   docker-compose -f docker-compose-production.yml up --detach
#   docker-compose -f docker-compose-production.yml up
#
# FIXME: fix import issue of the backend container
# -----------------------------------------------------------------------------
version: '3'

volumes:
  vue_dist:
    driver: local
  node_modules:
    driver: local

services:

  backend:
    restart: always
    build: .
    volumes:
      - .:/code
    environment:
      - MODULE_NAME="sbmlutils.report.api"
      - VARIABLE_NAME="api"
    expose:
      - "80"
    ports:
      - "1444:80"
    command: ["/start.sh"] # bash -c "/start.sh"

  frontend:
    build:
      context: ./sbml4humans
      dockerfile: Dockerfile-production
    command: tail -f /dev/null
    volumes:
      - ./sbml4humans:/app
      - node_modules:/app/node_modules/
      - vue_dist:/vue

  nginx:
    restart: always
    image: nginx:1.19.2
    ports:
      - 8084:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - vue_dist:/vue
    depends_on:
      - backend
      - frontend
    links:
      - backend:backend
